networks:
  default:

services:
  roamy-postgres:
    container_name: roamy-postgres
    image: postgres:17-alpine
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_DB=$POSTGRES_DATABASE
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
      -  postgres-volume:/var/lib/postgresql/data
    networks:
      - default

volumes: 
  postgres-volume: